import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BasicTypewriter from "../components/examples/BasicTypewriter";
import CustomCursorTypewriter from "../components/examples/CustomCursorTypewriter";
import CustomTypewriter from "../components/examples/CustomTypewriter";
import TypewriterWithLoop from "../components/examples/TypewriterWithLoop";
import PartialBackspaceTypewriter from "../components/examples/PartialBackspaceTypewriter";

const Home: NextPage = () => {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Documentation For the use-typewriter-hook Library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="typewriter typewriter-1">
          <PartialBackspaceTypewriter />
        </div>
        <div className="typewriter typewriter-2">
          <BasicTypewriter />
        </div>
        <div className="typewriter typewriter-3">
          <CustomCursorTypewriter />
        </div>
        <div className="typewriter typewriter-4">
          <CustomTypewriter />
        </div>
        <div className="typewriter typewriter-5">
          <TypewriterWithLoop />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
